
# annotations
ANNO = "../annotation"
ANNO_PREFIX = "Homo_sapiens.GRCh37.75.cdna.pc"
ANNO_FA = "{0}/{1}.fa".format( ANNO, ANNO_PREFIX )

# tool-specific indices
IDX = "../index"

RSEM_REF = "{0}/{1}_rsem/ref".format( IDX, ANNO_PREFIX )

N_THREADS = 20

# list of k to run simulation on
K_LIST = [i for i in range(15, 76, 4)]

rule all:
    input:
        expand("no_error_sim_30000000_1.fq.gz" )


# one directory with:
# rsem_params/
# simulated fastq
# results with different k

# make rsem simulator inputs
# just make one rsem simulation
# run kallisto-sailfish for various values of k

########################################################################
# INDICES
########################################################################

# Prepare the main annotation to run RSEM on it
rule rsem_prepare:
    input:
        ANNO_FA
    output:
        "{0}.grp".format( RSEM_REF )
    run:
        out_dir = '{0}/{1}_rsem'.format( IDX, ANNO_PREFIX )
        shell('mkdir -p {0}'.format( out_dir ) )
        shell('rsem-prepare-reference {0} {1}'.format( ANNO_FA, RSEM_REF ))


########################################################################
# GENERATE SIMULATION
########################################################################

# Simulate from RSEM without errors
rule rsem_simulate:
    output:
        "no_error_sim_{n_reads}_1.fq.gz",
        "no_error_sim_{n_reads}_2.fq.gz"
    threads: 1
    run:
        cmd = " ".join([
            "rsem-simulate-reads",
            RSEM_REF,
            "rsem_params/out.stat/out.model",
            "rsem_params/out.isoforms.results",
            "0.0",
            "{wildcards.n_reads}",
            "no_error_sim_{wildcards.n_reads}",
            "--seed 42"
            ])
        shell(cmd)
        shell("gzip no_error_sim*.fq")
