rule all:
    input:
        'bowtie2_version.txt',
        'kallisto_version.txt',
        'sailfish_version.txt',
        'tophat2_version.txt',
        'rsem_version.txt',
        'salmon_version.txt',
        'express_version.txt'

rule bowtie2_version:
    output: 'bowtie2_version.txt'
    shell:
        'bowtie2 --version &> bowtie2_version.txt'

rule kallisto_version:
    output: 'kallisto_version.txt'
    shell:
        'kallisto version &> kallisto_version.txt'

rule sailfish_version:
    output: 'sailfish_version.txt'
    shell:
        'sailfish --version &> sailfish_version.txt'

rule tophat2_version:
    output: 'tophat2_version.txt'
    shell:
        'tophat2 --version &> tophat2_version.txt'

rule rsem_version:
    output: 'rsem_version.txt'
    shell:
        'rsem-calculate-expression --help &> rsem_version.txt'

rule express_version:
    output: 'express_version.txt'
    shell:
        'express --help &> express_version.txt'

rule salmon_version:
    output: 'salmon_version.txt'
    shell:
        'salmon --version &> salmon_version.txt'
